version: '3.8'

services:
  flair-backend:
    build:
      context: .
      target: backend
    env_file: .env
    command: manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - ./db.sqlite3:/app/db.sqlite3
      - ./flair/uploads:/app/files
      - ./flair/static:/app/static
