# Generated by Django 3.1.7 on 2021-04-20 02:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlairType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=64, verbose_name='Text displayed on django server for flair')),
                ('reddit_flair_text', models.CharField(max_length=16, verbose_name='Emoji or Text that will be added if selected.')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FlairsAwarded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=20, verbose_name='A reddit username')),
                ('pub_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('flair_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flair.flairtype')),
            ],
        ),
    ]
