# Generated by Django 3.1.7 on 2021-04-21 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0002_flairsawarded_flairtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='flairsawarded',
            name='note',
            field=models.CharField(default='', max_length=255, verbose_name='A note on why this was awarded.'),
        ),
        migrations.AlterField(
            model_name='flairsawarded',
            name='pub_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
