# Generated by Django 3.1.7 on 2021-04-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0003_auto_20210421_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flairsawarded',
            old_name='pub_date',
            new_name='date_added',
        ),
    ]
