# Generated by Django 3.1.7 on 2021-04-22 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0004_auto_20210421_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='flairtype',
            name='note',
            field=models.CharField(default='', max_length=255, verbose_name='An optional note about this flair.'),
        ),
        migrations.AlterField(
            model_name='flairsawarded',
            name='note',
            field=models.CharField(default='', max_length=255, verbose_name='An optional note on why this was awarded.'),
        ),
    ]
