# Generated by Django 3.1.7 on 2021-04-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0005_auto_20210423_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='flairtype',
            name='static_image',
            field=models.CharField(default='', max_length=255, verbose_name='Server image path. Used by wiki page.'),
        ),
        migrations.AddField(
            model_name='flairtype',
            name='wiki_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flairtype',
            name='wiki_text',
            field=models.CharField(default='', max_length=65536, verbose_name='Information displayed on the flair wiki page.'),
        ),
    ]
