# Generated by Django 3.1.7 on 2021-04-28 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0006_auto_20210428_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flairsawarded',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='An optional note on why this was awarded.'),
        ),
        migrations.AlterField(
            model_name='flairtype',
            name='note',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='An optional note about this flair.'),
        ),
        migrations.AlterField(
            model_name='flairtype',
            name='static_image',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Server image path. Used by wiki page.'),
        ),
        migrations.AlterField(
            model_name='flairtype',
            name='wiki_text',
            field=models.CharField(blank=True, default='', max_length=65536, verbose_name='Information displayed on the flair wiki page.'),
        ),
    ]
