# Generated by Django 3.1.7 on 2021-04-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0007_auto_20210428_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='flairtype',
            name='flair_type',
            field=models.CharField(default='default', max_length=255, verbose_name='Flairs Type'),
        ),
    ]
