# Generated by Django 3.1.7 on 2021-04-30 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0009_auto_20210429_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='flairtype',
            name='reddit_flair_css',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='CSS class that will be added if selected.'),
        ),
    ]
