# Generated by Django 3.1.7 on 2021-05-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0011_auto_20210430_1605'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flairtype',
            old_name='reddit_flair_text',
            new_name='reddit_flair_emoji',
        ),
    ]
