# Generated by Django 3.1.7 on 2021-05-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0012_auto_20210501_2358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flairtype',
            name='reddit_flair_css_class',
        ),
    ]
