# Generated by Django 3.1.7 on 2021-05-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0013_remove_flairtype_reddit_flair_css_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='flairtype',
            name='reddit_flair_text',
            field=models.CharField(blank=True, max_length=64, verbose_name='Text that will be added if selected.'),
        ),
        migrations.AlterField(
            model_name='flairtype',
            name='reddit_flair_emoji',
            field=models.CharField(max_length=16, verbose_name='Emoji that will be added if selected.'),
        ),
    ]
