# Generated by Django 3.1.7 on 2021-05-01 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0015_flairtype_reddit_flair_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flairtype',
            name='reddit_flair_template_id',
            field=models.CharField(blank=True, max_length=36, verbose_name="Reddit's Template ID to set if any"),
        ),
    ]
