# Generated by Django 3.1.7 on 2021-05-11 08:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0016_auto_20210502_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionLogging',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=256, verbose_name='Action attempted.')),
                ('action_info', models.CharField(max_length=256, verbose_name='Info related to the action.')),
                ('reddit_name', models.CharField(max_length=20, verbose_name='Redditor name.')),
                ('error', models.CharField(max_length=256, verbose_name='Error message.')),
                ('current_flair', models.CharField(max_length=256, verbose_name='Current user flair if relevant.')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp at database insert time.')),
            ],
        ),
    ]
