# Generated by Django 3.1.7 on 2021-05-11 09:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0018_remove_actionlogging_current_flair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlogging',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Timestamp of event.'),
        ),
    ]
