# Generated by Django 3.1.7 on 2021-05-16 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0019_auto_20210511_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlogging',
            name='user_agent',
            field=models.CharField(max_length=65536, null=True, verbose_name='The user-agent string from the user.'),
        ),
    ]
