# Generated by Django 3.1.7 on 2021-05-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0020_actionlogging_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='flairtype',
            name='wiki_title',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Title of the flair displayed on the wiki.'),
        ),
    ]
