# Generated by Django 3.1.7 on 2021-07-20 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0021_flairtype_wiki_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlairDisplay',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_tierd', models.BooleanField(default=False)),
                ('reddit_flair_emoji', models.CharField(max_length=16, verbose_name='Emoji that will be added if selected.')),
                ('static_image', models.CharField(blank=True, default='', max_length=255, verbose_name='Server image path. Used by wiki page.')),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='flairtype',
            name='reddit_flair_emoji',
        ),
        migrations.RemoveField(
            model_name='flairtype',
            name='static_image',
        ),
        migrations.AlterField(
            model_name='flairsawarded',
            name='flair_id',
            field=models.ForeignKey(limit_choices_to=models.Q(('flair_type', 'award'), ('flair_type', 'tiered-award'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='flair.flairtype'),
        ),
        migrations.AlterField(
            model_name='flairtype',
            name='flair_type',
            field=models.CharField(choices=[('default', 'Default'), ('award', 'Award'), ('tiered-award', 'Tiered-Award'), ('temporary', 'Temporary')], default='default', max_length=255, verbose_name='Flairs Type'),
        ),
        migrations.AlterField(
            model_name='flairtype',
            name='wiki_display',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='flairtype',
            name='flair_tier',
            field=models.ManyToManyField(to='flair.FlairDisplay'),
        ),
    ]
