# Generated by Django 3.1.7 on 2021-07-20 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0022_auto_20210720_2210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flairtype',
            old_name='flair_tier',
            new_name='flair_display',
        ),
    ]
