# Generated by Django 3.1.7 on 2021-07-22 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0023_auto_20210722_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='flairsawarded',
            name='override',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='flairsawarded',
            name='override_reddit_flair_emoji',
            field=models.CharField(default='', max_length=16, verbose_name='Emoji that will be added if selected.'),
        ),
        migrations.AddField(
            model_name='flairsawarded',
            name='override_static_image',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Server image path. Overrides default for Flair_id selected.'),
        ),
    ]
