# Generated by Django 3.1.7 on 2021-07-20 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0023_auto_20210720_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flairdisplay',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
