# Generated by Django 3.1.7 on 2021-07-22 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0024_auto_20210720_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='flairsawarded',
            name='tier_rank',
            field=models.IntegerField(default=0, verbose_name='If this is a tiered-award, what rank is it?'),
        ),
        migrations.AlterField(
            model_name='flairdisplay',
            name='rank',
            field=models.IntegerField(default=0, verbose_name='If this is a tiered-award, what rank is it?'),
        ),
    ]
