# Generated by Django 3.1.7 on 2021-07-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0025_auto_20210722_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flairsawarded',
            name='override_reddit_flair_emoji',
            field=models.CharField(blank=True, default='', max_length=16, verbose_name='Override Emoji'),
        ),
    ]
