# Generated by Django 3.1.7 on 2021-07-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0026_auto_20210722_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flairtype',
            name='flair_type',
            field=models.CharField(choices=[('default', 'Default'), ('award', 'Award'), ('temporary', 'Temporary'), ('override', 'Override')], default='default', max_length=255, verbose_name='Flairs Type'),
        ),
        migrations.AlterField(
            model_name='flairtype',
            name='wiki_display',
            field=models.BooleanField(default=True),
        ),
    ]
