# Generated by Django 3.1.7 on 2021-07-25 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0027_auto_20210725_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flairsawarded',
            name='override_reddit_flair_emoji',
        ),
        migrations.RemoveField(
            model_name='flairsawarded',
            name='override_static_image',
        ),
        migrations.AddField(
            model_name='flairsawarded',
            name='override_flair',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(flair_type='override'), null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='override_flair', to='flair.flairtype'),
        ),
    ]
