# Generated by Django 3.1.13 on 2022-12-20 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0029_auto_20221122_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flairtype',
            name='static_image',
        ),
    ]
