# Generated by Django 3.1.13 on 2022-12-20 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0029_auto_20221122_0558'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flairtype',
            name='static_image',
        ),
        migrations.AlterField(
            model_name='flairsawarded',
            name='flair_id',
            field=models.ForeignKey(limit_choices_to=models.Q(('flair_type', 'achievement'), ('flair_type', 'custom'), ('flair_type', 'temporary'), _connector='OR'), null=True, on_delete=django.db.models.deletion.SET_NULL, to='flair.flairtype'),
        ),
    ]
