# Generated by Django 3.1.13 on 2023-01-28 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flair', '0030_auto_20221220_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title_jp', models.CharField(max_length=255, verbose_name='Japanese title')),
                ('title_en', models.CharField(max_length=255, verbose_name='English title')),
                ('alias', models.CharField(blank=True, max_length=255, verbose_name='Other aliases')),
            ],
            options={
                'verbose_name_plural': 'anime',
            },
        ),
        migrations.AlterModelOptions(
            name='flairassigned',
            options={'verbose_name': 'Currently set flair'},
        ),
        migrations.AlterField(
            model_name='flairtype',
            name='display_image',
            field=models.ImageField(upload_to='flair_images', verbose_name='Display image'),
        ),
        migrations.AlterField(
            model_name='flairtype',
            name='display_name',
            field=models.CharField(max_length=128, verbose_name='Display name'),
        ),
        migrations.AddField(
            model_name='flairtype',
            name='anime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flair.anime'),
        ),
    ]
