name: Build and deploy

# Update every time we push to the main branch
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Start SSH agent
      uses: webfactory/ssh-agent@v0.4.1
      with:
        ssh-private-key: ${{ secrets.FLAIRSITE_SSH_KEY }}

    - name: Create GitHub deployment
      uses: chrnorm/deployment-action@v1.0.0
      id: github_deployment
      with:
        token: ${{ github.token }}
        target_url: https://flair.r-anime.moe
        environment: production

    - name: Pull latest changes to server
      run: |
        ssh -o StrictHostKeyChecking=no flairsite@flair.r-anime.moe /bin/bash << 'EOF'
          # Causes this script to exit early and report a failure if any command errors
          set -e

          # Checkout latest changes from our repo, overwriting any local changes
          cd "$HOME/flairsite"
          git fetch --all
          git reset --hard origin/master

          # Use our virtualenv
          source .venv/bin/activate

          # Install dependencies
          pip3 install -r requirements.txt

          # Run migrations, pulling environment variables from the .env file
          python3 manage.py migrate

          # Collect all static files into STATIC_ROOT
          python3 manage.py collectstatic --noinput

          # Restart the service to make the new stuff go live
          sudo systemctl restart flairsite.service
        EOF

    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@v1.0.0
      with:
        token: ${{ github.token }}
        state: success
        deployment_id: ${{ steps.github_deployment.outputs.deployment_id }}

    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@v1.0.0
      with:
        token: ${{ github.token }}
        state: failure
        deployment_id: ${{ steps.github_deployment.outputs.deployment_id }}
